/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    proyectos: Proyecto;
    servicios: Servicio;
    testimonios: Testimonio;
    categorias: Categoria;
    medios: Medio;
    usuarios: Usuario;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    proyectos: ProyectosSelect<false> | ProyectosSelect<true>;
    servicios: ServiciosSelect<false> | ServiciosSelect<true>;
    testimonios: TestimoniosSelect<false> | TestimoniosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    medios: MediosSelect<false> | MediosSelect<true>;
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'pagina-inicio': PaginaInicio;
    'ajustes-sitio': AjustesSitio;
  };
  globalsSelect: {
    'pagina-inicio': PaginaInicioSelect<false> | PaginaInicioSelect<true>;
    'ajustes-sitio': AjustesSitioSelect<false> | AjustesSitioSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * El corazon del portafolio. Cada trabajo que quieras mostrar va aqui.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos".
 */
export interface Proyecto {
  id: number;
  /**
   * Como quieres que aparezca en la portada. Ej: "Identidad para Cafe Botanica".
   */
  titulo: string;
  /**
   * Se genera solo a partir del titulo. Editalo unicamente si sabes lo que haces: cambiarlo rompe los enlaces que ya circulan.
   */
  slug?: string | null;
  /**
   * Los destacados salen primero y mas grandes en la pagina de inicio.
   */
  destacado?: boolean | null;
  /**
   * Sirven para filtrar el portafolio.
   */
  categorias?: (number | Categoria)[] | null;
  /**
   * Horizontal y de buena calidad. Es la primera impresion del proyecto.
   */
  portada: number | Medio;
  /**
   * Una o dos frases. Se muestra bajo el titulo en el listado.
   */
  resumen: string;
  cliente?: string | null;
  anio?: number | null;
  /**
   * Opcional.
   */
  enlace?: string | null;
  /**
   * Ej: Naming, Identidad visual, Packaging. Arrastra para reordenar.
   */
  servicios?:
    | {
        nombre: string;
        id?: string | null;
      }[]
    | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Arrastra las filas para cambiar el orden en que se muestran.
   */
  galeria?:
    | {
        imagen: number | Medio;
        pie?: string | null;
        anchoCompleto?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Si lo dejas vacio se usa el titulo del proyecto. Ideal: 50-60 caracteres.
   */
  metaTitulo?: string | null;
  /**
   * Si lo dejas vacio se usa el resumen corto. Ideal: 150-160 caracteres.
   */
  metaDescripcion?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Etiquetas para agrupar los proyectos: Branding, Web, Fotografia...
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nombre: string;
  /**
   * Se genera solo a partir del titulo. Editalo unicamente si sabes lo que haces: cambiarlo rompe los enlaces que ya circulan.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Todas las imagenes del sitio. Se suben una vez y se reutilizan donde haga falta.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios".
 */
export interface Medio {
  id: number;
  /**
   * Describe la imagen en una frase. Lo leen los buscadores y los lectores de pantalla. Ej: "Fachada del restaurante al atardecer".
   */
  alt: string;
  /**
   * Opcional. Si la foto es de un fotografo externo, ponlo aqui.
   */
  credito?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    miniatura?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tarjeta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    ancha?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Lo que ofreces. Se listan en la portada.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios".
 */
export interface Servicio {
  id: number;
  titulo: string;
  /**
   * Dos o tres frases explicando en que consiste.
   */
  descripcion: string;
  /**
   * Se muestra sobre el titulo de la tarjeta.
   */
  icono?: ('estrella' | 'pincel' | 'camara' | 'codigo' | 'megafono') | null;
  /**
   * Menor numero = aparece antes.
   */
  orden?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lo que dicen tus clientes. Puedes ocultar uno sin borrarlo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios".
 */
export interface Testimonio {
  id: number;
  /**
   * Citalo tal cual lo dijo el cliente. Corto funciona mejor.
   */
  texto: string;
  autor: string;
  cargo?: string | null;
  empresa?: string | null;
  /**
   * Opcional. Cuadrada queda mejor.
   */
  foto?: (number | null) | Medio;
  /**
   * Desmarcalo para esconderlo sin perderlo.
   */
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quien puede entrar a este panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  /**
   * El editor puede crear y publicar contenido, pero no tocar usuarios ni ajustes tecnicos.
   */
  rol: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'proyectos';
        value: number | Proyecto;
      } | null)
    | ({
        relationTo: 'servicios';
        value: number | Servicio;
      } | null)
    | ({
        relationTo: 'testimonios';
        value: number | Testimonio;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'medios';
        value: number | Medio;
      } | null)
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos_select".
 */
export interface ProyectosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  destacado?: T;
  categorias?: T;
  portada?: T;
  resumen?: T;
  cliente?: T;
  anio?: T;
  enlace?: T;
  servicios?:
    | T
    | {
        nombre?: T;
        id?: T;
      };
  descripcion?: T;
  galeria?:
    | T
    | {
        imagen?: T;
        pie?: T;
        anchoCompleto?: T;
        id?: T;
      };
  metaTitulo?: T;
  metaDescripcion?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicios_select".
 */
export interface ServiciosSelect<T extends boolean = true> {
  titulo?: T;
  descripcion?: T;
  icono?: T;
  orden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios_select".
 */
export interface TestimoniosSelect<T extends boolean = true> {
  texto?: T;
  autor?: T;
  cargo?: T;
  empresa?: T;
  foto?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medios_select".
 */
export interface MediosSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        miniatura?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tarjeta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        ancha?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * El texto grande de la portada y la seccion "sobre mi".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicio".
 */
export interface PaginaInicio {
  id: number;
  /**
   * La frase grande de arriba. Corta y directa.
   */
  titular: string;
  subtitulo?: string | null;
  imagenHero?: (number | null) | Medio;
  sobreMi?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Datos que se repiten en todas las paginas: logo, contacto, redes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ajustes-sitio".
 */
export interface AjustesSitio {
  id: number;
  nombreSitio: string;
  /**
   * Aparece en Google bajo el nombre del sitio.
   */
  descripcion?: string | null;
  logo?: (number | null) | Medio;
  email?: string | null;
  telefono?: string | null;
  ciudad?: string | null;
  /**
   * Añade solo las que uses. Arrastra para ordenar.
   */
  redes?:
    | {
        plataforma: 'instagram' | 'behance' | 'linkedin' | 'dribbble' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pagina-inicio_select".
 */
export interface PaginaInicioSelect<T extends boolean = true> {
  titular?: T;
  subtitulo?: T;
  imagenHero?: T;
  sobreMi?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ajustes-sitio_select".
 */
export interface AjustesSitioSelect<T extends boolean = true> {
  nombreSitio?: T;
  descripcion?: T;
  logo?: T;
  email?: T;
  telefono?: T;
  ciudad?: T;
  redes?:
    | T
    | {
        plataforma?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}